--luau
--!strict
-- UIElementsData.luau
-- Module containing a mapping of UI element names to their Roblox asset IDs.

local UIElementsData = {}

UIElementsData.Icons = {
    ["Alliance"] = "rbxassetid://128203268160479",
    ["Community Goals"] = "rbxassetid://97149848004338",
    ["Challenges"] = "rbxassetid://120333480860384",
    ["Guest Pass"] = "rbxassetid://110319251186892",
    ["Tutorial"] = "rbxassetid://98150393120956",
    ["Settings"] = "rbxassetid://72876573893033",
    ["Rebirth"] = "rbxassetid://129409029383961",
    ["Staff Management"] = "rbxassetid://89834599810886",
    ["Upgrades"] = "rbxassetid://132635366103906",
    ["Achievements"] = "rbxassetid://79337595530955",
}

return UIElementsData